### ISSUE TITLE
Determine why `MouseEvent` is not working

### ISSUE THREAD

**Issue by lazops** [lazops/rustea#3]
Running the `mouse_event` example doesn't work properly.

**Comment by tonyb983** [comment]
Add this line to the `initialize` function in `rustea/lib.rs`, after calling `execute!(stdout, cursor::Hide)?;`:
```rust
execute!(stdout, crossterm::event::EnableMouseCapture)?;
```

**Comment by lazops** [comment]
Merged in the PR. It was missing a de-initialization of the mouse capture, but I added it.
